-- CreateTable
CREATE TABLE "Menu" (
    "MenuId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Prince" REAL NOT NULL,
    "StartDate" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "EndDate" DATETIME NOT NULL,
    "FoodId" INTEGER NOT NULL,
    FOREIGN KEY ("FoodId") REFERENCES "FoodItem" ("FoodId") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "FoodItem" (
    "FoodId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Name" TEXT NOT NULL,
    "Quantity" REAL NOT NULL,
    "UnitPrice" REAL NOT NULL,
    "CategoryId" INTEGER NOT NULL,
    FOREIGN KEY ("CategoryId") REFERENCES "Category" ("CategoryId") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "Category" (
    "CategoryId" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Nmae" TEXT NOT NULL
);
